---
- hosts: TestServer
  tasks:
    - name: Tasks to delete user on UNIX Endpoints as per the SR
      include_role:
        name: jtb_unix_user_delete
        tasks_from: main.yml
        apply:
          become: true
          
      when: ansible_facts['os_family']
        in ['RedHat', 'Suse', 'AIX', 'Debian']

  

